version: '3.8'

services:
  ollama:
    environment:
      # Required for some Mac setups to allow connection from other containers
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS="*"
    # Start.sh will select this file if on macOS
